"""
Tests for zip_near_miss.py — NearMissSimulator and ZIPNearMissModel.

All tests run on synthetic data generated by NearMissSimulator so no
external data is required. We use small simulations to keep the test
suite fast.
"""

from __future__ import annotations

import numpy as np
import polars as pl
import pytest

from insurance_telematics.zip_near_miss import (
    NearMissSimulator,
    ZIPNearMissModel,
    _DEFAULT_EVENT_TYPES,
)
from insurance_telematics.risk_aggregator import aggregate_to_driver
from insurance_telematics.trip_simulator import TripSimulator
from insurance_telematics.preprocessor import clean_trips
from insurance_telematics.feature_extractor import extract_trip_features


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def weekly_data_3group():
    """100 drivers x 26 weeks, 3 groups. Used for most fit tests."""
    sim = NearMissSimulator(n_groups=3, seed=42)
    return sim.simulate(n_drivers=100, n_weeks=26)


@pytest.fixture(scope="module")
def fitted_model(weekly_data_3group):
    """Pre-fitted 3-group ZIP model for predict tests."""
    model = ZIPNearMissModel(n_groups=3, random_state=42, max_iter=30)
    model.fit(weekly_data_3group)
    return model


# ---------------------------------------------------------------------------
# 1. Simulator smoke tests
# ---------------------------------------------------------------------------


class TestNearMissSimulator:
    def test_output_shape(self):
        sim = NearMissSimulator(n_groups=3, seed=0)
        df = sim.simulate(n_drivers=50, n_weeks=10)
        assert df.shape[0] == 50 * 10
        expected_cols = {"driver_id", "week_id", "exposure_km", "true_group"} | set(
            _DEFAULT_EVENT_TYPES
        )
        assert expected_cols.issubset(set(df.columns))

    def test_non_negative_counts(self):
        sim = NearMissSimulator(seed=1)
        df = sim.simulate(n_drivers=30, n_weeks=8)
        for et in _DEFAULT_EVENT_TYPES:
            assert df[et].min() >= 0, f"Negative counts in {et}"

    def test_positive_exposure(self):
        sim = NearMissSimulator(seed=2)
        df = sim.simulate(n_drivers=20, n_weeks=4)
        assert df["exposure_km"].min() > 0.0

    def test_group_labels_in_range(self):
        n_groups = 3
        sim = NearMissSimulator(n_groups=n_groups, seed=3)
        df = sim.simulate(n_drivers=60, n_weeks=5)
        assert df["true_group"].min() >= 0
        assert df["true_group"].max() < n_groups

    def test_single_group(self):
        sim = NearMissSimulator(n_groups=1, seed=4)
        df = sim.simulate(n_drivers=10, n_weeks=3)
        assert df["true_group"].unique().to_list() == [0]

    def test_single_week(self):
        sim = NearMissSimulator(seed=5)
        df = sim.simulate(n_drivers=20, n_weeks=1)
        assert df.shape[0] == 20


# ---------------------------------------------------------------------------
# 2. Model fit convergence
# ---------------------------------------------------------------------------


class TestZIPNearMissModelFit:
    def test_fit_returns_self(self, weekly_data_3group):
        model = ZIPNearMissModel(n_groups=3, max_iter=10, random_state=0)
        result = model.fit(weekly_data_3group)
        assert result is model

    def test_log_likelihood_non_decreasing(self, weekly_data_3group):
        """EM must not decrease the observed-data log-likelihood."""
        model = ZIPNearMissModel(n_groups=3, max_iter=30, random_state=42)
        model.fit(weekly_data_3group)
        ll = model.log_likelihood_history_
        assert len(ll) >= 2
        # Allow tiny numerical wobble but no significant decrease
        diffs = np.diff(ll)
        assert np.all(diffs >= -0.5), f"LL decreased by more than 0.5: {diffs.min():.4f}"

    def test_mixing_weights_sum_to_one(self, fitted_model):
        total = float(fitted_model.mixing_weights_.sum())
        assert abs(total - 1.0) < 1e-6, f"Mixing weights sum to {total}"

    def test_mixing_weights_non_negative(self, fitted_model):
        assert np.all(fitted_model.mixing_weights_ >= 0)

    def test_posteriors_shape(self, weekly_data_3group, fitted_model):
        n_drivers = weekly_data_3group.select("driver_id").unique().shape[0]
        assert fitted_model.group_posteriors_.shape == (n_drivers, 3)

    def test_posteriors_sum_to_one(self, fitted_model):
        row_sums = fitted_model.group_posteriors_.sum(axis=1)
        assert np.allclose(row_sums, 1.0, atol=1e-6), "Posterior rows do not sum to 1"

    def test_zip_params_all_groups_present(self, fitted_model):
        assert set(fitted_model.zip_params_.keys()) == {0, 1, 2}

    def test_zip_params_valid_values(self, fitted_model):
        for g, params in fitted_model.zip_params_.items():
            pi = params["pi"]
            lam = params["lambda_per_km"]
            assert 0.0 <= pi <= 1.0, f"Group {g} pi={pi} out of range"
            assert lam >= 0.0, f"Group {g} lambda={lam} < 0"


# ---------------------------------------------------------------------------
# 3. Group recovery (approximate — probabilistic test)
# ---------------------------------------------------------------------------


class TestGroupRecovery:
    def test_dominant_group_majority_accuracy(self):
        """
        With well-separated groups, dominant predicted group should agree with
        true group for >60% of drivers (above chance level of 33%).
        """
        sim = NearMissSimulator(n_groups=3, seed=7)
        df = sim.simulate(n_drivers=150, n_weeks=52)

        model = ZIPNearMissModel(n_groups=3, max_iter=50, random_state=7)
        model.fit(df)
        features = model.driver_risk_features(df)

        # Ground truth: one row per driver
        true_groups = (
            df.group_by("driver_id")
            .agg(pl.col("true_group").first())
            .sort("driver_id")
        )
        features_sorted = features.sort("driver_id")

        # Allow for label permutation: find best matching permutation
        from itertools import permutations

        true_g = true_groups["true_group"].to_numpy()
        pred_g = np.array(features_sorted["dominant_group"].to_list())

        best_acc = 0.0
        for perm in permutations(range(3)):
            remapped = np.array([perm[p] for p in pred_g])
            acc = float((remapped == true_g).mean())
            best_acc = max(best_acc, acc)

        assert best_acc > 0.55, (
            f"Best-permutation group recovery accuracy {best_acc:.2%} < 55%. "
            "Groups may not be well-separated enough."
        )


# ---------------------------------------------------------------------------
# 4. predict_group_probs
# ---------------------------------------------------------------------------


class TestPredictGroupProbs:
    def test_output_columns(self, fitted_model, weekly_data_3group):
        probs = fitted_model.predict_group_probs(weekly_data_3group)
        expected_cols = {"driver_id", "prob_group_0", "prob_group_1", "prob_group_2"}
        assert expected_cols.issubset(set(probs.columns))

    def test_probabilities_sum_to_one(self, fitted_model, weekly_data_3group):
        probs = fitted_model.predict_group_probs(weekly_data_3group)
        prob_cols = [f"prob_group_{g}" for g in range(3)]
        row_sums = sum(probs[c] for c in prob_cols)
        assert (row_sums - 1.0).abs().max() < 1e-5

    def test_output_n_rows(self, fitted_model, weekly_data_3group):
        probs = fitted_model.predict_group_probs(weekly_data_3group)
        n_drivers = weekly_data_3group.select("driver_id").unique().shape[0]
        assert probs.shape[0] == n_drivers


# ---------------------------------------------------------------------------
# 5. predict_rate
# ---------------------------------------------------------------------------


class TestPredictRate:
    def test_rates_non_negative(self, fitted_model, weekly_data_3group):
        rates = fitted_model.predict_rate(weekly_data_3group)
        for et in _DEFAULT_EVENT_TYPES:
            col = f"predicted_rate_{et}"
            assert rates[col].min() >= 0.0, f"Negative rate in {col}"

    def test_output_shape(self, fitted_model, weekly_data_3group):
        rates = fitted_model.predict_rate(weekly_data_3group)
        n_drivers = weekly_data_3group.select("driver_id").unique().shape[0]
        assert rates.shape[0] == n_drivers
        assert rates.shape[1] == 1 + len(_DEFAULT_EVENT_TYPES)  # driver_id + rates


# ---------------------------------------------------------------------------
# 6. driver_risk_features — join with aggregate_to_driver
# ---------------------------------------------------------------------------


class TestDriverRiskFeaturesJoin:
    def test_join_with_aggregate_to_driver(self, weekly_data_3group):
        """driver_risk_features() must join cleanly to aggregate_to_driver() output."""
        # Simulate trip data for the same set of drivers
        sim = TripSimulator(seed=42)
        trips_df, _ = sim.simulate(
            n_drivers=20,
            trips_per_driver=10,
            min_trip_duration_s=60,
            max_trip_duration_s=300,
        )
        trip_features = extract_trip_features(clean_trips(trips_df))
        driver_agg = aggregate_to_driver(trip_features)

        # Simulate near-miss data for the same drivers
        nm_sim = NearMissSimulator(n_groups=2, seed=42)
        # Use same driver IDs as trip data
        driver_ids_from_trips = driver_agg["driver_id"].to_list()
        weekly = nm_sim.simulate(n_drivers=len(driver_ids_from_trips), n_weeks=10)
        # Remap driver IDs to match trip drivers
        id_map = {
            f"DRV{i:04d}": driver_ids_from_trips[i]
            for i in range(len(driver_ids_from_trips))
        }
        weekly = weekly.with_columns(
            pl.col("driver_id").replace(id_map)
        )

        model = ZIPNearMissModel(n_groups=2, max_iter=20, random_state=0)
        model.fit(weekly)
        zip_features = model.driver_risk_features(weekly)

        # Join should succeed without error and produce correct shape
        combined = driver_agg.join(zip_features, on="driver_id", how="left")
        assert combined.shape[0] == driver_agg.shape[0]
        assert "dominant_group" in combined.columns
        assert "nme_rate_per_km" in combined.columns


# ---------------------------------------------------------------------------
# 7. ZIGP variant
# ---------------------------------------------------------------------------


class TestZIGPVariant:
    def test_zigp_fits_without_error(self, weekly_data_3group):
        model = ZIPNearMissModel(
            n_groups=2,
            use_generalised=True,
            max_iter=15,
            random_state=1,
        )
        model.fit(weekly_data_3group)
        assert len(model.zip_params_) == 2
        assert abs(model.mixing_weights_.sum() - 1.0) < 1e-6


# ---------------------------------------------------------------------------
# 8. Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    def test_single_group_degenerates_to_zip(self):
        sim = NearMissSimulator(n_groups=1, seed=10)
        df = sim.simulate(n_drivers=30, n_weeks=8)
        model = ZIPNearMissModel(n_groups=1, max_iter=20, random_state=0)
        model.fit(df)
        assert model.mixing_weights_.shape == (1,)
        assert abs(float(model.mixing_weights_[0]) - 1.0) < 1e-6

    def test_single_week(self):
        sim = NearMissSimulator(n_groups=2, seed=11)
        df = sim.simulate(n_drivers=40, n_weeks=1)
        model = ZIPNearMissModel(n_groups=2, max_iter=15, random_state=0)
        model.fit(df)
        probs = model.predict_group_probs(df)
        assert probs.shape[0] == 40

    def test_missing_required_column_raises(self):
        sim = NearMissSimulator(seed=12)
        df = sim.simulate(n_drivers=10, n_weeks=4)
        df_bad = df.drop("exposure_km")
        model = ZIPNearMissModel(n_groups=2)
        with pytest.raises(ValueError, match="exposure_km"):
            model.fit(df_bad)

    def test_predict_before_fit_raises(self):
        sim = NearMissSimulator(seed=13)
        df = sim.simulate(n_drivers=10, n_weeks=4)
        model = ZIPNearMissModel(n_groups=2)
        with pytest.raises(RuntimeError, match="fit"):
            model.predict_group_probs(df)
